In [5]:
import NumPy as np

ModuleNotFoundError: No module named 'NumPy'

In [2]:
import Numpy as np

ModuleNotFoundError: No module named 'Numpy'

In [6]:
import numpy as np


In [4]:
a=np.array([1,2,3,4])

In [5]:
print(a)


[1 2 3 4]


In [8]:
a= np.arange(6)

In [9]:
print(a)

[0 1 2 3 4 5]


In [10]:
np.random.random(6)

array([0.01168919, 0.31641028, 0.08943269, 0.97226699, 0.85130743,
       0.3144251 ])

In [11]:
a.shape(0)


TypeError: 'tuple' object is not callable

In [12]:
a.shape


(6,)

In [13]:
np.zeros(4)


array([0., 0., 0., 0.])

In [14]:
np.arrange(6,2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [15]:
np.arrange([6,2])

AttributeError: module 'numpy' has no attribute 'arrange'

In [16]:
np.arange(6,2)

array([], dtype=int64)

In [20]:
np.arange(6,2)

array([], dtype=int64)

In [24]:
b=np.arange(6).reshape(3,2)

In [25]:
b.shape


(3, 2)

In [31]:
np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

In [33]:
b=np.arange(6)

In [34]:
c=np.arange(6)

In [35]:
np.dot(b,c)

55

In [36]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [1]:
np.random

NameError: name 'np' is not defined

In [7]:
np.random.random_sample(4)

array([0.86152131, 0.8400125 , 0.75842787, 0.23510021])

In [8]:
np.random.random(5)

array([0.31141872, 0.4442391 , 0.58599499, 0.68463101, 0.50906928])

In [11]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
a = np.arange(4);              
print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0 1 2 3], a shape = (4,), a data type = int64
